# SFMPE (Structured Flow Matching for Posterior Estimation) Configuration
# Configuration for the Transformer-based structured CNF

# Transformer neural network configuration
transformer:
  latent_dim: 64
  label_dim: 8
  index_out_dim: 0
  n_encoder: 1
  n_decoder: 1
  n_heads: 2
  n_ff: 2
  dropout: 0.1