# SVEIR Flow Matching Configuration
# Configuration for SVEIR epidemiological model with functional random variables

defaults:
  - sfmpe: indexed
  - fmpe: default
  - _self_

# SVEIR model parameters
n_timesteps: 1850   # Total simulation timesteps
n_obs: 25           # Number of observations to sample
n_sites: 20         # Number of observation sites
n_warmup: 1850      # Warmup period to exclude initial epidemic dynamics

# ODE simulation parameters
dt: 1.0            # Time step size (days)
population: 10000  # Population size
I0_prop: 0.001     # Initial infection proportion

# Training parameters  
n_simulations: 1000  # Number of simulations per round
n_rounds: 1         # Number of training rounds  
n_epochs: 100       # Number of epochs per round

# Model hyperparameters
n_post_samples: 1000  # Number of posterior samples

# F_in_sample
f_in_sample: "prior" # Options: "observed", "prior"

# Training configuration
training:
  learning_rate: 3e-4
  batch_size_fraction: 0.1  # Fraction of n_simulations for batch size

# Analysis parameters
analysis:
  n_cal: 1000        # Number of calibration samples
  n_cal_epochs: 100  # Number of calibration epochs
  n_null: 100        # Number of null classifiers
  classifier:
    latent_dim: 16
    n_layers: 2

# Random seed
seed: 42
