# SVEIR Flow Matching Configuration
# Configuration for SVEIR epidemiological model with functional random variables

defaults:
  - sfmpe: indexed
  - _self_

# SEIR model parameters
n_timesteps: 1850   # Total simulation timesteps
n_obs: 25            # Number of observations to sample
n_sites: 2          # Number of observation sites
n_warmup: 1850      # Warmup period to exclude initial epidemic dynamics

# ODE simulation parameters
dt: 1.0            # Time step size (days)
population: 10000  # Population size
I0_prop: 0.001     # Initial infection proportion

# N prior
n_prior_samples: 1000

# Training parameters  
n_simulations: 1000 # Number of simulations per round
n_rounds: 1        # Number of training rounds
n_epochs: 1000     # Number of epochs per round

# Model hyperparameters
n_post_samples: 100  # Number of posterior samples

# F_in_sample
f_in_sample: "prior" # Options: "observed", "prior"

# Training configuration
training:
  learning_rate: 3e-4
  batch_size_fraction: 0.1  # Fraction of n_simulations for batch size

# MCMC configuration
mcmc:
  sampler: "slice"  # Options: "slice", "nuts", "ess"
  use_numpyro_model: false  # Use NumPyro model instead of manual log_prob (NUTS/ESS only)
  n_chains: 4
  step_size: 0.001
  max_doublings: 3
  max_tree_depth: 5

# Method selection
method: "MCMC"  # Options: "MCMC", "SFMPE"

# Inference configuration - selective parameter sampling
inference:
  sample_params: null  # List of parameters to sample, e.g. ["beta_0"] for beta-0 only
                       # If null, samples all parameters (default behavior)
                       # Available params: ["beta_0", "alpha", "sigma", "A", "T_season", "phi"]

# SFMPE configuration (used when method: "SFMPE")
sfmpe:
  transformer:
    latent_dim: 64
    label_dim: 16
    index_out_dim: 32
    n_encoder: 2
    n_decoder: 2
    n_heads: 4
    n_ff: 256
    dropout: 0.1

# Random seed
seed: 42
